SET SERVEROUTPUT ON

-- EX1
DECLARE 
CURSOR V_JOB IS SELECT JOB_TITLE, JOB_ID 
                FROM JOBS;
CURSOR V_EMP IS SELECT LAST_NAME, FIRST_NAME, JOB_ID
                FROM EMPLOYEES;
V_TITLU JOBS.JOB_TITLE%TYPE;
V_COD JOBS.JOB_ID%TYPE;
V_NUME EMPLOYEES.LAST_NAME%TYPE;
V_PRENUME EMPLOYEES.FIRST_NAME%TYPE;
V_COD2 V_COD%TYPE;

BEGIN
OPEN V_JOB;
LOOP
    FETCH V_JOB INTO V_TITLU, V_COD;
    EXIT WHEN V_JOB%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('------------');
    DBMS_OUTPUT.PUT_LINE(V_TITLU);
    DBMS_OUTPUT.PUT_LINE('------------');
    OPEN V_EMP;
    LOOP
        FETCH V_EMP INTO V_NUME, V_PRENUME, V_COD2;
        EXIT WHEN V_EMP%NOTFOUND;
        IF V_COD = V_COD2 THEN
            DBMS_OUTPUT.PUT_LINE(V_NUME || ' ' || V_PRENUME);
        END IF;
    END LOOP;
    CLOSE V_EMP;
END LOOP;
CLOSE V_JOB;

END;
/

-- 2
select *
from employees;



