-- 1) 
SELECT CONCAT(CONCAT(FIRST_NAME, ' '),LAST_NAME)||' castiga '||SALARY||'lunar, dar doreste '|| 3*SALARY AS "SALARIUL IDEAL"
FROM EMPLOYEES;

-- 2)
SELECT INITCAP(FIRST_NAME)||' '||UPPER(LAST_NAME)||' '||LENGTH(LAST_NAME)
FROM EMPLOYEES
WHERE (LAST_NAME LIKE 'J%' OR LAST_NAME LIKE 'M%' OR LAST_NAME LIKE '__A%')
ORDER BY LENGTH(LAST_NAME) DESC;

SELECT INITCAP(FIRST_NAME)||' '||UPPER(LAST_NAME)||' '||LENGTH(LAST_NAME)
FROM EMPLOYEES
WHERE (SUBSTR(LAST_NAME, 1,1) LIKE  'J' OR SUBSTR(LAST_NAME,1,1) LIKE 'M' OR SUBSTR(LAST_NAME, 3,1) LIKE 'A')
ORDER BY LENGTH(LAST_NAME) DESC;

-- 3)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE LTRIM(RTRIM(UPPER(first_name)))='STEVEN';

-- 4)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, LENGTH(LAST_NAME) AS "Lungime nume", INSTR(LOWER(LAST_NAME),'a') AS "Aparitie"
FROM EMPLOYEES
WHERE (LAST_NAME LIKE '%e');

-- 5)
SELECT *
FROM EMPLOYEES
WHERE (MOD(ROUND(SYSDATE - HIRE_DATE),7) = 0);

-- 6)
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, ROUND(SALARY* 1.15,2) AS "SALARIU NOU", ROUND(SALARY*1.15/100,2) AS "NUMAR SUTE"
FROM EMPLOYEES
WHERE MOD(SALARY, 1000)!=0;

-- 7)
SELECT LAST_NAME AS "NUME ANGAJAT", RPAD(TO_CHAR(HIRE_DATE),20,' ') AS "DATA ANGAJARII"
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

-- 8)
SELECT TO_CHAR(SYSDATE+30, 'MONTH DD HH24:MM:SS') AS "DATA"
FROM DUAL;

-- 9)
SELECT ROUND(TO_DATE('31-DEC-2018') - SYSDATE) 
FROM DUAL;

-- 10)
SELECT TO_CHAR(SYSDATE+12/24, 'DD/MM HH24:MI:SS') AS "Data"
FROM DUAL;
SELECT TO_CHAR(SYSDATE+5/60/24, 'DD/MM HH24:MI:SS') AS "ZIUA"
FROM DUAL;

-- 11)
SELECT FIRST_NAME||' '||LAST_NAME AS "Nume si prenume",HIRE_DATE, NEXT_DAY(ADD_MONTHS(HIRE_DATE,6), 'Monday') AS "Negociere"
FROM EMPLOYEES;

-- 12)
SELECT FIRST_NAME, LAST_NAME, ROUND(MONTHS_BETWEEN(SYSDATE, hire_date)) AS "LUNI LUCRATE"
FROM EMPLOYEES
ORDER BY MONTHS_BETWEEN(SYSDATE, HIRE_DATE);

-- 13)  
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE, TO_CHAR(HIRE_DATE, 'DAY') AS "ZI"
FROM EMPLOYEES
ORDER BY (TO_CHAR(HIRE_DATE - 1 ,'D'));

-- 14) 
SELECT FIRST_NAME, LAST_NAME, NVL(TO_CHAR(COMMISSION_PCT),'Fara Comision') AS "Comision"
FROM EMPLOYEES;

-- 15) 
SELECT LAST_NAME, SALARY, COMMISSION_PCT, SALARY + SALARY * NVL(COMMISSION_PCT, 0)
FROM EMPLOYEES
WHERE SALARY + SALARY * NVL(COMMISSION_PCT,0) > 10000;

-- 16)
SELECT LAST_NAME, JOB_ID, SALARY, DECODE (JOB_ID,'IT_PROG', SALARY*1.2, 'SA_REP', SALARY*1.25, 'SA_MAN', SALARY*1.35, SALARY) AS "Salariu renegociat"
FROM EMPLOYEES;

SELECT LAST_NAME, JOB_ID, SALARY, 
CASE JOB_ID WHEN 'IT_PROG' THEN SALARY*1.2
            WHEN 'SA_REP' THEN SALARY*1.25
            WHEN 'SA_MAN' THEN SALARY*1.35
            ELSE SALARY 
            END 
AS "Salariu renegociat"
FROM EMPLOYEES;

-- 17)
SELECT EMPLOYEES.LAST_NAME, EMPLOYEES.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES, DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID;

SELECT E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID; 

-- 18)
SELECT DISTINCT E.JOB_ID, J.JOB_TITLE
FROM EMPLOYEES E, JOBS J
WHERE E.JOB_ID=J.JOB_ID AND E.DEPARTMENT_ID=30;

-- 19)
SELECT E.LAST_NAME, D.DEPARTMENT_NAME, L.CITY, E.COMMISSION_PCT
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID AND COMMISSION_PCT IS NOT NULL;

-- 20)
SELECT E.LAST_NAME,D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID AND INSTR(LOWER(FIRST_NAME),'a')=0;

-- 21)
SELECT E.LAST_NAME,J.JOB_TITLE, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L, JOBS J
WHERE (E.DEPARTMENT_ID=D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID) AND (L.CITY='Oxford') AND (E.JOB_ID=J.JOB_ID);

-- 22)
SELECT E.EMPLOYEE_ID Ang#, E.LAST_NAME Angajat, E.MANAGER_ID Mgr#, M.LAST_NAME Manager
FROM EMPLOYEES E, EMPLOYEES M
WHERE E.MANAGER_ID=M.EMPLOYEE_ID;

-- 23)
SELECT E.EMPLOYEE_ID Ang#, E.LAST_NAME Angajat, E.MANAGER_ID Mgr#, M.LAST_NAME Manager
FROM EMPLOYEES E, EMPLOYEES M
WHERE E.MANAGER_ID=M.EMPLOYEE_ID(+);

-- 24)
SELECT E.LAST_NAME,E.DEPARTMENT_ID,C.LAST_NAME AS "COLEG"
FROM EMPLOYEES E, EMPLOYEES C
WHERE E.DEPARTMENT_ID=C.DEPARTMENT_ID AND E.EMPLOYEE_ID>C.EMPLOYEE_ID;

-- 25) 
SELECT E.FIRST_NAME, E.LAST_NAME, E.JOB_ID, J.JOB_TITLE, D.DEPARTMENT_NAME, E.SALARY
FROM EMPLOYEES E, JOBS J, DEPARTMENTS D
WHERE E.JOB_ID=J.JOB_ID AND E.DEPARTMENT_ID=D.DEPARTMENT_ID(+);

-- 26) 
SELECT E.LAST_NAME, E.HIRE_DATE
FROM EMPLOYEES E, EMPLOYEES G
WHERE LOWER(G.LAST_NAME)='gates' AND E.HIRE_DATE > G.HIRE_DATE;

-- 27)
SELECT E.LAST_NAME Angajat, E.HIRE_DATE Data_ang, M.LAST_NAME Manager, M.HIRE_DATE Data_mgr
FROM EMPLOYEES E, EMPLOYEES M
WHERE E.MANAGER_ID=M.EMPLOYEE_ID AND E.HIRE_DATE < M.HIRE_DATE;





