-- i)
SELECT E.LAST_NAME,E.JOB_ID,J.JOB_TITLE,D.DEPARTMENT_NAME,E.SALARY
FROM EMPLOYEES E, JOBS J, DEPARTMENTS D
WHERE
    j.job_id = e.job_id
    AND   e.department_id = d.department_id
        AND   (
        salary < 2000
        OR    TO_CHAR(hire_date,'YYYY') = '1987'
    );     


-- j)
-- WHERE
SELECT E.LAST_NAME, E.SALARY, J.JOB_TITLE, L.CITY, C.COUNTRY_NAME
FROM EMPLOYEES E, JOBS J, LOCATIONS L, DEPARTMENTS D, COUNTRIES C
WHERE J.JOB_ID = E.JOB_ID AND E.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.LOCATION_ID=L.LOCATION_ID AND C.COUNTRY_ID = L.COUNTRY_ID AND E.MANAGER_ID=100; 

--JOIN ON / EQUIJOIN
SELECT E.LAST_NAME, E.SALARY, J.JOB_TITLE, L.CITY, C.COUNTRY_NAME
FROM EMPLOYEES E JOIN JOBS J ON (J.JOB_ID = E.JOB_ID)
                 JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
                 JOIN LOCATIONS L ON (D.LOCATION_ID=L.LOCATION_ID)
                 JOIN COUNTRIES C ON (C.COUNTRY_ID = L.COUNTRY_ID)
WHERE E.MANAGER_ID=100; 

-- JOIN USING / NATURAL JOIN
SELECT E.LAST_NAME, E.SALARY, J.JOB_TITLE, L.CITY, C.COUNTRY_NAME
FROM EMPLOYEES E JOIN JOBS J USING (JOB_ID)
                 JOIN DEPARTMENTS D USING (DEPARTMENT_ID)
                 JOIN LOCATIONS L USING (LOCATION_ID)
                 JOIN COUNTRIES C USING (COUNTRY_ID)
WHERE E.MANAGER_ID=100; 

-- n)
SELECT DISTINCT E.EMPLOYEE_ID, E.LAST_NAME
FROM EMPLOYEES E, EMPLOYEES E2
WHERE E.DEPARTMENT_ID=E2.DEPARTMENT_ID AND LOWER(E2.LAST_NAME) LIKE '%t%';

-- o)
SELECT DISTINCT E.EMPLOYEE_ID, E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E, EMPLOYEES E2, DEPARTMENTS D
WHERE E.DEPARTMENT_ID=E2.DEPARTMENT_ID AND LOWER(E2.LAST_NAME) LIKE '%t%' AND E.DEPARTMENT_ID=D.DEPARTMENT_ID;


select *
from employees e natural join employees e2;

-- p)
SELECT last_name, department_name
FROM departments d, employees e
WHERE d.department_id(+) = e.department_id;

-- q)
SELECT department_name, last_name
FROM departments d, employees e
WHERE d.department_id = e.department_id(+);

-- r)
SELECT last_name, department_name
FROM employees e, departments d
WHERE e.department_id = d.department_id(+)
UNION
SELECT last_name, department_name
FROM employees e, departments d
WHERE e.department_id(+) = d.department_id;

SELECT DISTINCT last_name, department_name
FROM employees e FULL OUTER JOIN departments d
ON e.department_id = d.department_id;

-- s)
SELECT D.DEPARTMENT_ID
FROM DEPARTMENTS D
WHERE LOWER(D.DEPARTMENT_NAME) LIKE '%re%'
UNION
SELECT DEPARTMENT_ID
FROM EMPLOYEES E
WHERE E.JOB_ID='SA_REP';

-- t)
SELECT DEPARTMENTS_ID
FROM DEPARTMENTS
MINUS
SELECT DEPARTMENTS_ID
FROM DEPARTMENTS D, EMPLOYEES E
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID;

-- u)
SELECT D.DEPARTMENT_ID
FROM DEPARTMENTS D
WHERE LOWER(D.DEPARTMENT_NAME) LIKE '%re%'
INTERSECT
SELECT DEPARTMENT_ID
FROM EMPLOYEES E
WHERE E.JOB_ID='HR_REP';

-- 20)
SELECT LAST_NAME,SALARY
FROM EMPLOYEES
WHERE MANAGER_ID = (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE MANAGER_ID IS NULL);